### PR TITLE
VisiCut Connect - Thingiverse Integration

### PR DESCRIPTION
**Pull request by tur0kk**
A user-friendly enhancement of VisiCut to browse, filter and open your Thingiverse files in VisiCut.
Developed during the MCP class.

GitHub Issue: 
https://github.com/t-oster/VisiCut/issues/221

### CODE REVIEW

**Comment by t-oster** [comment]
Hi, please clear the commit log with git-rebase -i, meaning:
 * rebase your branch on top of develop, so it is a clean fast-forward (no "merge"-commits)
 * put commits which belong together in one commit (e.g. not 3x update readme)
 * merge commits which are correcting other commits, so it looks like it was done right the first time

**Comment by renebohne** [comment]
No status update for 5 days... are there problems with the things that Thomas requested?

**Comment by t-oster** [comment]
I just tested the feature and I like it. Please fix the history, or I will just merge all changes in one commit (which will then have my name on it).

**Comment by tur0kk** [comment]
We will fix the thingiverse and the Facebook Integration next week.

**Comment by t-oster** [comment]
superseeded by #245

**Pull request closed without merging**
