### PR TITLE
french translation

### PR DESCRIPTION
**Pull request by clemclemmm**

### CODE REVIEW

**Comment by clemclemmm** [comment]
did you get the files @t-oster or i have to do something else ? (merge the branch maybe ?)

**Comment by t-oster** [comment]
Hi thanks for contributung. I will merge it this afternoon

**Comment by t-oster** [comment]
I had to fix the naming and encoding, but now it should work. The version is compiling right now, so should be available for download in the next few minutes

**Comment by clemclemmm** [comment]
Great !
First download is me :)

ClemClem

Le 8 oct. 2017 à 14:34, Thomas Oster <notifications@github.com<mailto:notifications@github.com>> a écrit :


I had to fix the naming and encoding, but now it should work. The version is compiling right now, so should be available for download in the next few minutes

**Pull request merged**
