### PR TITLE
Ignore continuous tag properly

### PR DESCRIPTION
**Pull request by TheAssassin**
Please see the diff for an in-depth explanation.

This should fix local builds, too. CC @jnweiger

### CODE REVIEW

**Comment by TheAssassin** [comment]
Small reminder that this small but important fix is still waiting for a merge.

**Review by jnweiger — APPROVED** [review]
Thanks!
Looks good to me. 
Please merge.

**Comment by mgmax** [comment]
Thanks :-)

Can we now remove the workaround here?

https://github.com/t-oster/VisiCut/blob/master/.github/workflows/github-build.yml#L37

**Comment by TheAssassin** [comment]
Yep. Although I see no pressure to do so.

**Comment by mgmax** [comment]
I removed the workaround now.

**Pull request merged**
