### PR TITLE
Fix and improve build process

### PR DESCRIPTION
**Pull request by mgmax**
- Fix errors in distribute.sh
- Makefile / distribute.sh: Always update the splash screen, do not rely on cached image with possibly outdated version number
- distribute.sh: show where resulting EXE file was stored

VisicutBuilder must also be updated; a separate PR will follow.

### CODE REVIEW

**Comment by mgmax** [comment]
can be merged as soon as https://github.com/t-oster/VisicutBuilder/pull/11 is merged and the container build job https://gitlab.com/t-oster/visicutbuildservice/-/jobs/ ran successfully

**Comment by t-oster** [comment]
Hi, 
I merged the builder part but it does not run successfully:

```
uildservice_1      | ++ cut -d= -f2
buildservice_1      | ++ grep Application.version
buildservice_1      | ++ tr -d ' '
buildservice_1      | + VERSION=1.9-195-gbaeb9a62
buildservice_1      | + [[ 1.9-195-gbaeb9a62 != '' ]]
buildservice_1      | + log 'Using properties-provided version 1.9-195-gbaeb9a62'
buildservice_1      | + [[ -t 0 ]]
buildservice_1      | + [[ -t 0 ]]
buildservice_1      | + echo '== Using properties-provided version 1.9-195-gbaeb9a62 =='
buildservice_1      | == Using properties-provided version 1.9-195-gbaeb9a62 ==
buildservice_1      | + [[ -t 0 ]]
visicutbuildservice_buildservice_1 exited with code 1

**Comment by t-oster** [comment]
Should this be merged anyway?

**Comment by t-oster** [comment]
@mgmax Thank you for taking care

**Pull request merged**
