### PR TITLE
FabQR system integration, use QR codes for project identification

### PR DESCRIPTION
**Pull request by FroChr123**
This is the final pull request, which should be production ready, at least I could not find anything else, which needs to be done.

Short description of the concept of the project;
http://hci.rwth-aachen.de/fabqr

Older versions and some additional information can be found here:
https://github.com/t-oster/VisiCut/pull/276

Other related software projects:
https://github.com/FroChr123/visicamRPiGPU (GPU accelerated image processing for VisiCam)
https://github.com/FroChr123/FabQR (Software for webserver setup, support for projector images)

There is also the option to use the WebCam for loading QR codes, obviously without positioning / rotating of the objects. This is supposed to be a fallback for the users without a VisiCam setup.

For both setups multiple QR codes in one input image are supported aswell. Arbitrary QR codes containing a URL to any svg / plf file can be used, the QR codes do not need to be associated with the FabQR system.

Images say more than thousand words:
Example for user interaction with VisiCam:

visicut-qr-code-1
visicut-qr-code-2
visicut-qr-code-3
visicut-qr-code-4
visicut-qr-code-5
visicut-qr-code-6
visicut-qr-code-7
visicut-qr-code-8

GUI / Configuration stuff:

visicut-qr-code-9
visicut-qr-code-10
visicut-qr-code-11

### CODE REVIEW

**Comment by mgmax** [comment]
I didn't have time to try it out, but still have two quick remarks:
- Please clean up the commit history. It is annoying to have all these little changes flooding the commit history like some previous student projects did. Just look at the current public commit history, at some point there are dozens of useless entries like "prepared I made on publishing in gui - tur0kk".
- try to keep the changes for someone who does not actively use this as little as possible. I fear that a non-modified VisiCam server will crash or behave weirdly when there are three VisiCut instances open on different lab computers and these are continuously fetching images. Probably VisiCam needs some work so that it does not try to fetch camera images in parallel.

**Comment by FroChr123** [comment]
Hey, thanks for your feedback.

First point: I already used commit ammend a lot to keep the history clean, otherwise we would now probably have something about > 200 commits. :D But I can clean it up even more.

Second point: I tried to keep that in mind for most of the changes, most of the stuff can be deactivated / has fallbacks for older versions. :) I tried the multiple-access stuff with the modified setup, and with that it is still quite fast and near video-like. But now after your feedback I also tried and confirmed it for a slow setup, that everything still works correctly. I had to "synchronize" the VisiCam code in newer versions of VisiCam and that keeps everything stable, of course the refresh rate is still crap with this setup.

**Comment by FroChr123** [comment]
History cleaned up. :P

**Comment by FroChr123** [comment]
There will be a user study for evaluation purposes. I hope that the concept and the idea is clear and maybe you can also create such a setup for yourself to try it out.

If you are interested in participating, here is the link to the PDF file:
http://hci.rwth-aachen.de/tiki-download_wiki_attachment.php?attId=2347&page=fabqr&download=y

You can send the filled out PDF file to me:
fabqr@web.de

**Comment by mgmax** [comment]
cool. If I hope to test the VisiCam changes and continuous image fetching soon.

**Comment by FroChr123** [comment]
I am currently trying this on a Mac setup, as requested in another pull request, I might change the JavaAppStub file and as it seems Java version 1.7 is required as minimum version by the external libraries.

**Comment by FroChr123** [comment]
Results after trying to set it up for 8 freaking hours on a Mac OS X 10.7.5:
It's a mess.

The .app wrapper always requires the native Apple Java 6 installation, which is crap, if you need Java 7 for some features. Even modifying the minimum required Java Version in the .app package or exchanging the JavaAppStub file did not change anything.

Solution: Ignore the .app stuff, just use the .jar file and create an alias / shortcut to it and change the icon of the shortcut to the VisiCut icon (It worked like this: Create alias to Jar file, open MacIcons, Apple + C the largest icon, select alias file, Apple + I, select icon symbol, Apple + V the icon). Then it looks like VisiCut and can be opened with a default Jar file opener - and other Java versions.

As soon as QR code detection is enabled, minimum Java version 7 is required (disabled by default).

**Comment by t-oster** [comment]
Hi, what is the state of this pull request? Is it ready to be merged into develop?`Btw: I saw your presentation and I liked it. The improvements on VisiCam are very good. I am not sure if the QR part is useful in a non-research context, but if it does not bloat the whole thing too much, I am willing to integrate it.

**Comment by FroChr123** [comment]
Hi, thanks for your response. :)
This pull request should currently be fine, this version is now also running on the computers in the RWTH Aachen FabLab. Most stuff is configurable and can be deactivated, only the automatic fetching of camera images is currently always active.
I have some ideas for further improvements, but this is nothing which would be really important for any major part of this pull request, only minor changes.

**Pull request merged**
