### PR TITLE
inkscape extension: set path, probably fixes #258

### LINKED ISSUE #258: win8.1 and inkscape extension
@knatterman wrote into the manual that installing the inkscape extension does not work on win8.1
https://github.com/t-oster/VisiCut/wiki/VisiCut-manual#inkscape-and-illustrator-extensions

I cannot test this, but suppose that as long as you use the setup.exe this is already fixed by commit 3941b70c56518e61dc5eaa207d77ab15f7fbd782

We should still check why VisiCut does not put its path into the inkscape extension script.

### PR DESCRIPTION
**Pull request by mgmax**
At least under Win7 now we don't need to add visicut to the PATH anymore for using the inkscape plugin.
No idea about illustrator.

### CODE REVIEW

**Comment by t-oster** [comment]
Is this tested under Win, Linux and OSX?

**Comment by mgmax** [comment]
failed testing:
Linux (platform independant zip) because this only installs a 
"VisiCut.Linux" and no "visicut" file.
-> what's the point of the two files being different: 
distribute/linux/visicut and distribute/files/VisiCut.Linux ?
-> will re-test and open a new pullrequest

**Comment by mgmax** [comment]
see #261

**Comment by peteruithoven** [comment]
I'd love to help test this under OS X, but I'm afraid I don't understand the issue. 
What would I need to test?

**Comment by mgmax** [comment]
I only changed/repaired the way that the inkscape extension uses to find 
where visicut was installed.


short test description:


uninstall visicut

build the fixed version (from mgmax/tmp1, see #261), create MacOS 
package with:
cd distribute; ./distribute.sh
(answer "n" for all packages you don't need like windows etc.)

install the MacOS package you built
start visicut
choose "install inkscape extension" in visicut menu
start inkscape
see if visicut extension works (you can send files to visicut)

uninstall package, try the same for the platform-independant ZIP

**Comment by peteruithoven** [comment]
Alright, I checked out your `tmp1` branch and ran `distribute.sh`, but building failes:
```
$ ./distribute.sh 
Determining Version:
Version is: "1.7"
Building jar...

BUILD FAILED
/Developer/VisiCut/VisiCut-mgmax/nbproject/build-impl.xml:931: The following error occurred while executing this line:
/Developer/VisiCut/VisiCut-mgmax/nbproject/build-impl.xml:303: Compile failed; see the compiler error output for details.

Total time: 7 seconds
make: *** [jar] Error 1
```
Took me a while to figure out where to find the compiler error output. Maybe we should document this better. 
When I run make separately I get the following errors: 
```
-do-compile:
    [javac] Compiling 152 source files to /Developer/VisiCut/VisiCut-mgmax/build/classes
    [javac] /Developer/VisiCut/VisiCut-mgmax/src/com/tur0kk/thingiverse/gui/mapping/ThingCollectionComboboxModel.java:30: type javax.swing.ComboBoxModel does not take parameters
    [javac] public class ThingCollectionComboboxModel implements ComboBoxModel<ThingCollection>
    [javac]                                                                   ^
    [javac] /Developer/VisiCut/VisiCut-mgmax/src/com/tur0kk/thingiverse/gui/ThingiverseDialog.java:333: setModel(javax.swing.ComboBoxModel) in javax.swing.JComboBox cannot be applied to (com.tur0kk.thingiverse.gui.mapping.ThingCollectionComboboxModel)
    [javac]     cbCollection.setModel(comboboxModel);
    [javac]                 ^
    [javac] Note: /Developer/VisiCut/VisiCut-mgmax/src/com/t_oster/visicut/gui/beans/PreviewPanel.java uses or overrides a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 2 errors
```

**Comment by peteruithoven** [comment]
To help future me and others I started some docs: https://github.com/t-oster/VisiCut/wiki/Development:-Getting-started#distribution

**Pull request closed without merging**
