### PR TITLE
Automatic Object Arrangement

### PR DESCRIPTION
**Pull request by C4rmel**
We are still working on this, but you can have a look at it.

### CODE REVIEW

**Comment by peteruithoven** [comment]
I would really love to see a screenshot

**Comment by C4rmel** [comment]
Well a screenshot of this is not really spectacular since you only see arranged shapes :)

One interesting screen can be when the objects that you want to arrange do not fit all into the laserbed. We the try to maximise the used area and mark the pieces that can be removed to achieve this.

objectarrangerscreen

**Comment by peteruithoven** [comment]
Nice! 
So this arranges multiple files right? Not shapes in files right? 
If it's per file it might make more sense to put the Arrange button next to the file editing ui (File selector, add file button, remove file button). Because now it's grouped with view related buttons. I'll admit I'm not sure where to place it when it's not per file. 
I also assume the button only shows up when relevant? To keep the ui as minimal as possible for beginners.

**Comment by C4rmel** [comment]
thanks for the feedback!

Yes it is per file. In the beginning we tried to do it for shapes in files. But this has several problems since most SVGs usually are not grouped correctly so the arrangement process might separate parts that usually belong together. Also as far as I got this visicut strips down the SVG files into parts and does not maintain the group relation. We also got the feedback that the general case where this option would be useful is when you dump several files into VisiCut and it would be too tedious to arrange them by hand. So we made the decision to only arrange files.

Regarding the button: I need to admit that we did not put that much thought process into the actual position but more in the function behind it and what happens when you press it. We highly focused on the slider interface that you see on the right side. (Does not seem like a lot of work I know) but the whole interaction was way more complex before and so we did some user test and stripped down the whole interaction to this one slider that appears after you pressed the arrange button. We did test this with novice and experienced users. I will consider your feedback regarding the button position because you are right that it belongs more to the file interaction. We wrote a report for the Plugin and will also give a  talk where we talk about our design decisions and show the iterations of the interface and previous prototypes. As far as I know the talk gets recorded. I can put linkshere for the report and the talk when they get published.

**Comment by peteruithoven** [comment]
Really great to hear that you did user research. I do like the simplicity of the slider interface you guys created.
I'd love to see the talk.

**Comment by mgmax** [comment]
Did you try cutting and engraving multiple files at once on an epliog laser?
There will probably be a problem (although it is not your code to blame):
When I last tried this engraves the first item, cuts the first, engraves the second, cuts the second, and so on. Because of a driver limitation the job can only contain exactly one engrave part and then multiple cut parts. (TODO check this with the windows driver and colour mapping in the "advanced" tab)
Related: #104

**Comment by renebohne** [comment]
No status update for 5 days... are there problems with the things that Thomas requested?

**Comment by C4rmel** [comment]
Hey I am pretty interested in finishing this thing but at the moment I am realy busy. I am writing my bachelor thesis and I need to learn for exams. I can continue this project after the 17.03.

**Comment by t-oster** [comment]
Hi... any update on this?

**Comment by C4rmel** [comment]
I have to admit I forgot about this. I got in touch with my partner for this. We both are busy on September (exams and thesis month) but we plan to finish this on the beginning of October. We also got some more feedback from the final presentation at our chair.

**Comment by t-oster** [comment]
Please reopen if you find the time to continue.

**Pull request closed without merging**
