### PR TITLE
distribute.sh: Show correct version when building without VisiCutBuilder

### PR DESCRIPTION
**Pull request by mgmax**
Before, when building with distribute.sh without VisiCutBuilder, the window title showed a fixed fallback string for the version, and the splash screen always showed "1.7".

Now, when building without VisiCutBuilder, the right version (determined from $VERSION or from git) is shown in the splash screen, and the window title simply doesn't show the version.

Nothing has changed when building *with* VisiCutBuilder, which writes the version into VisicutApp.properties.

### CODE REVIEW

**Comment by t-oster** [comment]
Two questions:
- what happens if you do not use git ( download the zip from GitHub)?
- what happens when you run from netbeans?

**Comment by mgmax** [comment]
The zip from GitHub doesn't work anyway since it doesn't contain the LibLaserCut submodule.

Netbeans does not start distribute.sh. It also does not use the splash image. The window title in Netbeans will simply be "Visicut" instead of "Visicut 1.7".

**Comment by t-oster** [comment]
Ok, it would work if you previously download the liblasercut zip and mvn install it

**Comment by mgmax** [comment]
I don't think so because distribute.sh calls make, which assumes that LibLaserCut is in the correct subdirectory.

**Pull request merged**
