### PR TITLE
Fix GUI resizing. Fixes #262

### LINKED ISSUE #262: UI too wide for 1280x1024
on an average old TFT with 1024 pixels width, the UI does not fit and the "submit" button is clipped.
I tested this in german under win7 and debian, I measured a minimum width of 1360 pixels.

### PR DESCRIPTION
**Pull request by mgmax**
I did a second version which works even nicer.
I tested this under Linux and Win7 down to 1024x768. I don't have a Mac, it would be nice if someone can check if the GUI works properly and nothing is cut away in the right panel (for wide enough windows) when switching to a user-defined mapping or similar.
.
I rebased my commit so that you can merge it more easily.

At 1024x768 except the facebook/thingiverse buttons are "hidden" because there is not enough layout space.
At 1280x1024 everything is fine.

Changes:
- put zoom and other buttons inside a toolbar so that the rightmost ones disappear when there is not enough space
- removed some spacing
- changed resizability and default width attributes at a few places

done with netbeans 7.3.1 + swing plugin

tested on windows and linux

### CODE REVIEW

**Comment by peteruithoven** [comment]
I'd like to help, checking this on OS X, but don't really know Java, or it's workflow. 
I have *NetBeans IDE 7.3* I installed the *Swing Application Framework library* plugin (with no updates available). 
I'm getting the following build output:
```
ant -f /Developer/VisiCut/fix-gui-resizing clean jar
init:
deps-clean:
Updating property file: /Developer/VisiCut/fix-gui-resizing/build/built-clean.properties
LibLaserCut.init:
LibLaserCut.deps-clean:
Updating property file: /Developer/VisiCut/fix-gui-resizing/build/built-clean.properties
Deleting directory /Developer/VisiCut/fix-gui-resizing/lib/LibLaserCut/build
LibLaserCut.clean:
Deleting directory /Developer/VisiCut/fix-gui-resizing/build
clean:
init:
deps-jar:
Created dir: /Developer/VisiCut/fix-gui-resizing/build
Updating property file: /Developer/VisiCut/fix-gui-resizing/build/built-jar.properties
LibLaserCut.init:
LibLaserCut.deps-jar:
Created dir: /Developer/VisiCut/fix-gui-resizing/lib/LibLaserCut/build
Updating property file: /Developer/VisiCut/fix-gui-resizing/build/built-jar.properties
Created dir: /Developer/VisiCut/fix-gui-resizing/lib/LibLaserCut/build/classes
Created dir: /Developer/VisiCut/fix-gui-resizing/lib/LibLaserCut/build/empty
Created dir: /Developer/VisiCut/fix-gui-resizing/lib/LibLaserCut/build/generated-sources/ap-source-output
Compiling 53 source files to /Developer/VisiCut/fix-gui-resizing/lib/LibLaserCut/build/classes
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Copying 2 files to /Developer/VisiCut/fix-gui-resizing/lib/LibLaserCut/build/classes
LibLaserCut.compile:
Created dir: /Developer/VisiCut/fix-gui-resizing/lib/LibLaserCut/dist
Copy libraries to /Developer/VisiCut/fix-gui-resizing/lib/LibLaserCut/dist/lib.
Building jar: /Developer/VisiCut/fix-gui-resizing/lib/LibLaserCut/dist/LibLaserCut.jar
To run this application from the command line without Ant, try:
java -jar "/Developer/VisiCut/fix-gui-resizing/lib/LibLaserCut/dist/LibLaserCut.jar"
Building jar: /Developer/VisiCut/fix-gui-resizing/lib/LibLaserCut/dist/LibLaserCutWithDeps.jar
LibLaserCut.jar:
Created dir: /Developer/VisiCut/fix-gui-resizing/build/classes
Created dir: /Developer/VisiCut/fix-gui-resizing/build/empty
Compiling 152 source files to /Developer/VisiCut/fix-gui-resizing/build/classes
/Developer/VisiCut/fix-gui-resizing/src/com/tur0kk/thingiverse/gui/mapping/ThingCollectionComboboxModel.java:30: type javax.swing.ComboBoxModel does not take parameters
public class ThingCollectionComboboxModel implements ComboBoxModel<ThingCollection>
/Developer/VisiCut/fix-gui-resizing/src/com/tur0kk/thingiverse/gui/ThingiverseDialog.java:333: setModel(javax.swing.ComboBoxModel) in javax.swing.JComboBox cannot be applied to (com.tur0kk.thingiverse.gui.mapping.ThingCollectionComboboxModel)
    cbCollection.setModel(comboboxModel);
Note: /Developer/VisiCut/fix-gui-resizing/src/com/t_oster/visicut/gui/beans/PreviewPanel.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
/Developer/VisiCut/fix-gui-resizing/nbproject/build-impl.xml:931: The following error occurred while executing this line:
/Developer/VisiCut/fix-gui-resizing/nbproject/build-impl.xml:303: Compile failed; see the compiler error output for details.
BUILD FAILED (total time: 4 seconds)
```
But, this doesn't seem to be anything specific with your version, I get the same version with the latest *develop* of the regular *t-oster/VisiCut* version.

**Comment by t-oster** [comment]
you need to use a higher java version

**Comment by peteruithoven** [comment]
I think you underestimate how complex the java platform is for outsiders, there doesn't seem to be "Java", there is Java SE, EE, ME, JRE, JDK etc etc. Most of these have a version like 8.x. No 1.7 or 1.6.

**Comment by t-oster** [comment]
I am sorry. You need the JDK 1.7 aka 7 or higher. You probably just have to select it in Netbeans under project properties -> libraries -> java platform

**Comment by peteruithoven** [comment]
Thanks! Looks like I only have 1.6 available there, but I think I found both (1.)7 and (1.)8:
http://www.oracle.com/technetwork/java/javase/downloads/jdk7-downloads-1880260.html
http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

After installing the JDK 1.7 and restarting Netbeans compilation succeeded.

**Comment by peteruithoven** [comment]
Some first screenshots. Seems workable in very small size: 
screen shot 2015-05-18 at 02 11 49
screen shot 2015-05-18 at 02 12 29
Buttons disappear when no space is available: 
screen shot 2015-05-18 at 02 11 56
Execute available on the bottom: 
screen shot 2015-05-18 at 02 12 35

One weird thing, the button style (top left toolbar) changed, this is a screenshot with the regular button styles: 
screen shot 2015-05-18 at 02 13 10
The right part stays very thin when the size is increased, which is a bit of a shame: 
screen shot 2015-05-18 at 02 19 10

Let me know if I can test something specific.

**Comment by mgmax** [comment]
interesting; where has the "update photo" button gone?

**Comment by peteruithoven** [comment]
The selected printer doesn't have a camera (Camera url). A lasercutter with Camera configured: 
screen shot 2015-05-18 at 20 46 56
screen shot 2015-05-18 at 20 47 07

**Comment by mgmax** [comment]
I tried something new that also seems to work on linux and windows: Now the right pane is also resizable.
@peteruithoven can you check if it now is better on Mac?

**Comment by peteruithoven** [comment]
By resizable you mean its width is automatically adjusted? I shouldn't look for a ui element that allows me to adjust the width manually right? Two examples: 
screen shot 2015-05-18 at 21 47 44
screen shot 2015-05-18 at 21 48 48

Again a great improvement. Only after resizing the width smaller than about 970px parts of the right side are hidden, which is quite acceptable.

**Comment by mgmax** [comment]
Nice to hear that.

Yes, the divider is not movable. I tried that with JSplitPane but it is 
absolutely horrible.

**Pull request closed without merging**
